# Generated by Django 2.2.6 on 2019-10-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_termino',
            field=models.DateField(verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Horário do Início'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_termino',
            field=models.TimeField(verbose_name='Horário do Término'),
        ),
    ]
