# Generated by Django 2.2.6 on 2019-10-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20191023_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(verbose_name='data de início'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_termino',
            field=models.DateField(verbose_name='data de término'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_inicio',
            field=models.TimeField(verbose_name='horário do início'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='hora_termino',
            field=models.TimeField(verbose_name='horário do término'),
        ),
    ]
